//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.FindService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FindService.FinderServisSoap")]
    public interface FinderServisSoap {
        
        // CODEGEN: Generating message contract since element name word from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        ClientApp.FindService.FindResponse Find(ClientApp.FindService.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.FindService.FindResponse> FindAsync(ClientApp.FindService.FindRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.FindService.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(ClientApp.FindService.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.FindService.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(ClientApp.FindService.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(System.Xml.Linq.XElement FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinderServisSoapChannel : ClientApp.FindService.FinderServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinderServisSoapClient : System.ServiceModel.ClientBase<ClientApp.FindService.FinderServisSoap>, ClientApp.FindService.FinderServisSoap {
        
        public FinderServisSoapClient() {
        }
        
        public FinderServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinderServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinderServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinderServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.FindService.FindResponse ClientApp.FindService.FinderServisSoap.Find(ClientApp.FindService.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public System.Xml.Linq.XElement Find(string word) {
            ClientApp.FindService.FindRequest inValue = new ClientApp.FindService.FindRequest();
            inValue.Body = new ClientApp.FindService.FindRequestBody();
            inValue.Body.word = word;
            ClientApp.FindService.FindResponse retVal = ((ClientApp.FindService.FinderServisSoap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.FindService.FindResponse> ClientApp.FindService.FinderServisSoap.FindAsync(ClientApp.FindService.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.FindService.FindResponse> FindAsync(string word) {
            ClientApp.FindService.FindRequest inValue = new ClientApp.FindService.FindRequest();
            inValue.Body = new ClientApp.FindService.FindRequestBody();
            inValue.Body.word = word;
            return ((ClientApp.FindService.FinderServisSoap)(this)).FindAsync(inValue);
        }
    }
}
